version: "3.8"

services:
  drogon-app:
    build: .
    ports:
      - "8888:80"


  ssftp-server:
    image: atmoz/sftp
    ports:
      - "8890:22"
    volumes:
      - /home/default/workspace:/home/default/workspace
    command: default:default123:::workspace
