version: "3.8"

services:
  drogon-app:
    build: .
    volumes:
      - /home/default:/home/default
    ports:
      - "8888:80"

  sftp-server:
    image: atmoz/sftp
    ports:
      - "8890:22"
    volumes:
      - /home/default:/home/default
    command: default:default123:::workspace