version: "3.8"

services:
  drogon-app:
    build: .
    ports:
      - "8888:80"


  ssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: ssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      - PASSWORD_ACCESS=true
      - USER_NAME=default
      - USER_PASSWORD=default123
    volumes:
      - /home/default:/home/default
    ports:
      - "8890:2222"
    restart: unless-stopped
